apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgnn-anomaly-detection-deployment
  namespace: cloudsentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cgnn-anomaly-detection
  template:
    metadata:
      labels:
        app: cgnn-anomaly-detection
    spec:
      containers:
      - name: cgnn-anomaly-detection
        image: jojojochem/anomaly_detection_cgnn:latest
        ports:
        - containerPort: 5013

---
apiVersion: v1
kind: Service
metadata:
  name: cgnn-anomaly-detection-service
  namespace: cloudsentinel
spec:
  selector:
    app: cgnn-anomaly-detection
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5013
