apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestion-deployment
  namespace: cloudsentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-ingestion
  template:
    metadata:
      labels:
        app: data-ingestion
    spec:
      containers:
      - name: data-ingestion
        image: jojojochem/data_ingestion:latest
        ports:
        - containerPort: 5001
        env:
        - name: CELERY_BROKER_URL
          value: "redis://redis:6379/0"
        - name: CELERY_RESULT_BACKEND
          value: "redis://redis:6379/0"

---
apiVersion: v1
kind: Service
metadata:
  name: data-ingestion-service
  namespace: cloudsentinel
spec:
  selector:
    app: data-ingestion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-ingestion-sa
  namespace: cloudsentinel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cloudsentinel
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: cloudsentinel
subjects:
- kind: ServiceAccount
  name: data-ingestion-sa
  namespace: cloudsentinel
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-pods-global
subjects:
- kind: ServiceAccount
  name: data-ingestion-sa
  namespace: cloudsentinel
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io