apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processing-deployment
  namespace: cloudsentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-processing
  template:
    metadata:
      labels:
        app: data-processing
    spec:
      containers:
      - name: data-processing
        image: jojojochem/data_processing:${COMMIT_SHA}
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: data-processing-service
  namespace: cloudsentinel
spec:
  selector:
    app: data-processing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
