apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestion-deployment
  namespace: cloudsentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-ingestion
  template:
    metadata:
      labels:
        app: data-ingestion
    spec:
      containers:
      - name: data-ingestion
        image: jojojochem/data_ingestion:latest
        ports:
        - containerPort: 5001
        env:
        - name: CELERY_BROKER_URL
          value: "redis://redis:6379/0"
        - name: CELERY_RESULT_BACKEND
          value: "redis://redis:6379/0"

---
apiVersion: v1
kind: Service
metadata:
  name: data-ingestion-service
  namespace: cloudsentinel
spec:
  selector:
    app: data-ingestion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
