name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker build -t myrepo/data_ingestion:latest -f data_ingestion/Dockerfile data_ingestion/
        docker build -t myrepo/data_processing:latest -f data_processing/Dockerfile data_processing/
        docker build -t myrepo/anomaly_detection/cgnn:latest -f anomaly_detection/cgnn/Dockerfile anomaly_detection/cgnn/
        # docker build -t myrepo/anomaly_detection/crca:latest -f anomaly_detection/crca/Dockerfile anomaly_detection/crca/
        # docker build -t myrepo/learning_adaptation:latest -f learning_adaptation/Dockerfile learning_adaptation/
        # docker build -t myrepo/django:latest django:latest -f user_interface/monitoring_project/Dockerfile user_interface/monitoring_project/
        docker push myrepo/data_ingestion:latest
        docker push myrepo/data_processing:latest
        docker push myrepo/anomaly_detection/cgnn:latest
        # docker push myrepo/anomaly_detection/crca:latest
        # docker push myrepo/learning_adaptation:latest
        # docker push myrepo/django:latest

    - name: Set up Kubernetes
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/data_ingestion-deployment.yml
        kubectl apply -f k8s/data_processing-deployment.yml
        kubectl apply -f k8s/cgnn_anomaly_detection-deployment.yml
        kubectl apply -f k8s/crca_anomaly_detection-deployment.yml
        kubectl apply -f k8s/learning_adaptation-deployment.yml
        kubectl apply -f k8s/learning_adaptation-celery-deployment.yml
        kubectl apply -f k8s/crca_anomaly_detection-celery-deployment.yml
        kubectl apply -f k8s/celery-worker-deployment.yml
        kubectl apply -f k8s/redis-deployment.yml
        kubectl apply -f k8s/django-deployment.yml