# name: Data Ingestion Deployment

# on:
#   push:
#     paths:
#       - 'data_ingestion/**'

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Log in to Docker Hub
#       uses: docker/login-action@v3
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v3

#     - name: Build and push Docker image
#       run: |
#         docker build -t ${{ secrets.DOCKER_USERNAME }}/data_ingestion:latest -f data_ingestion/Dockerfile data_ingestion/
#         docker push ${{ secrets.DOCKER_USERNAME }}/data_ingestion:latest

#     - name: Set up Google Cloud SDK
#       uses: google-github-actions/setup-gcloud@v0
#       with:
#         version: 'latest'
#         service_account_key: ${{ secrets.GCP_SA_KEY }}
#         export_default_credentials: true

#     - name: Configure kubectl
#       run: |
#         gcloud container clusters get-credentials cscluster --zone us-central1-a --project cloudsentinel-427513

#     - name: Deploy to Kubernetes
#       run: |
#         kubectl apply -f k8s/data_ingestion-deployment.yml
#         kubectl apply -f k8s/data_ingestion_celery-deployment.yml
#         kubectl set image deployment/data-ingestion-deployment data-ingestion=${{ secrets.DOCKER_USERNAME }}/data_ingestion:latest -n cloudsentinel
#         kubectl set image deployment/celery-worker-deployment celery-worker=${{ secrets.DOCKER_USERNAME }}/data_ingestion:latest -n cloudsentinel
#         kubectl rollout restart deployment data-ingestion-deployment -n cloudsentinel
#         kubectl rollout restart deployment celery-worker-deployment -n cloudsentinel
