# name: Learning Adaptation Deployment

# on:
#   push:
#     paths:
#       - 'learning_adaptation/**'

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Log in to Docker Hub
#       uses: docker/login-action@v3
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v3

#     - name: Build and push Docker image
#       run: |
#         docker build -t ${{ secrets.DOCKER_USERNAME }}/learning_adaptation:latest -f learning_adaptation/Dockerfile learning_adaptation/
#         docker push ${{ secrets.DOCKER_USERNAME }}/learning_adaptation:latest

#     - name: Set up Google Cloud SDK
#       uses: google-github-actions/setup-gcloud@v0
#       with:
#         version: 'latest'
#         service_account_key: ${{ secrets.GCP_SA_KEY }}
#         export_default_credentials: true

#     - name: Configure kubectl
#       run: |
#         gcloud container clusters get-credentials cscluster --zone us-central1-a --project cloudsentinel-427513

#     - name: Deploy to Kubernetes
#       run: |
#         kubectl apply -f k8s/learning_adaptation-deployment.yml
#         kubectl apply -f k8s/learning_adaptation-celery-deployment.yml
#         kubectl set image deployment/learning-adaptation-deployment learning-adaptation=${{ secrets.DOCKER_USERNAME }}/learning_adaptation:latest -n cloudsentinel
#         kubectl set image deployment/learning-adaptation-celery-deployment learning-adaptation-celery=${{ secrets.DOCKER_USERNAME }}/learning_adaptation:latest -n cloudsentinel
#         kubectl rollout restart deployment learning-adaptation-deployment -n cloudsentinel
#         kubectl rollout restart deployment learning-adaptation-celery-deployment -n cloudsentinel
