name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache-new -t crca_anomaly_detection:latest -f anomaly_detection/crca/Dockerfile anomaly_detection/crca/
        docker build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache-new -t data_ingestion:latest -f data_ingestion/Dockerfile data_ingestion/
        docker build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache-new -t data_processing:latest -f data_processing/Dockerfile data_processing/
        docker build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache-new -t cgnn_anomaly_detection:latest -f anomaly_detection/cgnn/Dockerfile anomaly_detection/cgnn/
        docker build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache-new -t learning_adaptation:latest -f learning_adaptation/Dockerfile learning_adaptation/
        docker build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache-new -t django:latest -f user_interface/monitoring_project/Dockerfile user_interface/monitoring_project/
        docker tag crca_anomaly_detection:latest myrepo/anomaly_detection/crca:latest
        docker tag data_ingestion:latest myrepo/data_ingestion:latest
        docker tag data_processing:latest myrepo/data_processing:latest
        docker tag cgnn_anomaly_detection:latest myrepo/anomaly_detection/cgnn:latest
        docker tag learning_adaptation:latest myrepo/learning_adaptation:latest
        docker tag django:latest myrepo/django:latest
        docker push myrepo/anomaly_detection/crca:latest
        docker push myrepo/data_ingestion:latest
        docker push myrepo/data_processing:latest
        docker push myrepo/anomaly_detection/cgnn:latest
        docker push myrepo/learning_adaptation:latest
        docker push myrepo/django:latest

    - name: Save Docker cache
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache-new
        key: ${{ runner.os }}-buildx-${{ github.sha }}
