# name: Infrastructure Setup Deployment

# on:
#   push:
#     paths:
#       - 'k8s/**'

# jobs:
#   setup-infrastructure:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Google Cloud SDK
#       uses: google-github-actions/setup-gcloud@v0
#       with:
#         version: 'latest'
#         service_account_key: ${{ secrets.GCP_SA_KEY }}
#         export_default_credentials: true

#     - name: Configure kubectl
#       run: |
#         gcloud container clusters get-credentials cscluster --zone us-central1-a --project cloudsentinel-427513

#     - name: Check if Helm is installed
#       run: |
#         if ! command -v helm &> /dev/null; then
#           curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
#         else
#           echo "Helm is already installed"
#         fi

#     - name: Add Prometheus Helm repository if not already added
#       run: |
#         if ! helm repo list | grep -q 'prometheus-community'; then
#           helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
#           helm repo update
#         else
#           echo "Prometheus Helm repository is already added"
#         fi

#     - name: Deploy Prometheus if not already deployed
#       run: |
#         if ! kubectl get namespaces | grep -q 'monitoring'; then
#           kubectl create namespace monitoring || true
#         else
#           echo "Namespace 'monitoring' already exists"
#         fi

#         if ! helm list -n monitoring | grep -q 'prometheus'; then
#           helm install prometheus prometheus-community/prometheus -n monitoring
#         else
#           echo "Prometheus is already deployed in the 'monitoring' namespace"
#         fi

#     - name: Deploy Redis
#       run: |
#         kubectl apply -f k8s/redis-deployment.yml
